engines:
  duplication:
    enabled: true
    exclude_paths:
      - test/
    config:
      languages:
        php:
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
      standard: "PSR1"
  phpmd:
    enabled: true
    config:
      file_extensions:
        - php

ratings:
  paths:
  - src/**.php

exclude_paths:
  - docs
  - LICENSE
  - .travis.yml
  - .gitignore
  - README.md
  - composer.json
  - phpunit.xml
