#!/bin/bash

# Run phpdoc to create structure.xml
echo "Running phpdocumentor"
vendor/bin/phpdoc --force -n

# Run phpdoc-md to create Markdown files
echo "Running phpdoc-md"
vendor/bin/phpdocmd -i docs/documentation/structure.xml -o docs/documentation -t docs/assets/twig/