#!/bin/bash

# Clear output directory
rm -rf ../docs/documentation/*

# Run phpdoc to create structure.xml
vendor/bin/phpdoc

# Run phpdoc-md to create Markdown files
vendor/bin/phpdocmd docs/documentation/structure.xml docs/documentation